# Generated by Django 4.0.4 on 2022-05-19 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTuitlon', '0002_certificaciones_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificaciones',
        ),
    ]
