# Generated by Django 4.0.4 on 2022-05-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTuitlon', '0003_delete_certificaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuitl',
            name='imagen',
            field=models.ImageField(null=True, upload_to='tuitls'),
        ),
    ]
