# Generated by Django 4.0.4 on 2022-05-27 00:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTuitlon', '0005_alter_tuitl_fecha_alter_tuitl_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuitl',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
