# Generated by Django 4.0.4 on 2022-05-27 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTuitlon', '0007_alter_tuitl_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuitl',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='avatares'),
        ),
    ]
