# Generated by Django 4.0.4 on 2022-05-27 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTuitlon', '0008_alter_tuitl_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuitl',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
    ]
